// <auto-generated />
using System;
using DocumentRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentRepository.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241018155805_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocumentRepository.Models.DocumentModel", b =>
                {
                    b.Property<Guid>("documentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("documentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("documentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uploadedFile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("documentID");

                    b.ToTable("documentModels");
                });
#pragma warning restore 612, 618
        }
    }
}
